name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true  # Enables Git LFS

      - name: Build and Deploy
        run: |
          npm install
          npm run build
          npx gh-pages -d dist